# Generated by Django 5.2.7 on 2025-10-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CPVCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "application_deadline",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("award_period", models.DateField(blank=True, null=True)),
                ("expiration_time", models.DateTimeField(blank=True, null=True)),
                (
                    "bidders_requests_deadline",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("download_link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tender_number", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "tender_procedure",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "execution_place",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subdivision_into_lots", models.BooleanField(default=False)),
                ("side_offers_allowed", models.BooleanField(default=False)),
                ("several_main_offers_allowed", models.BooleanField(default=False)),
                (
                    "contracting_authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="core.contractor",
                    ),
                ),
                (
                    "cpv_codes",
                    models.ManyToManyField(
                        blank=True, related_name="publications", to="core.cpvcode"
                    ),
                ),
                (
                    "dates",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication",
                        to="core.publicationdates",
                    ),
                ),
                (
                    "tender_documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="publications",
                        to="core.publicationdocument",
                    ),
                ),
            ],
        ),
    ]
