# Generated by Django 5.2.7 on 2025-10-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="tender_documents",
        ),
        migrations.AddField(
            model_name="publication",
            name="portal",
            field=models.CharField(default="No Portal", max_length=100),
        ),
        migrations.AddField(
            model_name="publication",
            name="publication_url",
            field=models.URLField(default="https://www.google.com/"),
        ),
        migrations.AddField(
            model_name="publicationdocument",
            name="tender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tender_documents",
                to="core.publication",
            ),
        ),
    ]
